service: serverless-sample-http
useDotenv: true
frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: ap-northeast-1
  apiGateway:
    shouldStartNameWithService: true
    apiKeys:
      - myFirstKey
      - name: myAPIKey
        value: ${env:MY_API_KEY}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
          private: true
